name: Conatus
description: Informative app for CS/IT sociey "Conatus" of AKGEC.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  http: 0.12.0
  cached_network_image: 0.5.1
  connectivity: 0.4.0
  fluttertoast: 2.2.11
  progress_indicators: 0.1.2
  splashscreen: 1.2.0
  rxdart: 0.20.0

dev_dependencies:
  flutter_launcher_icons: "0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/drawer-background.png
    - assets/images/contact.png
    - assets/images/home.png
    - assets/images/code.png
    - assets/images/event.png
    - assets/images/faculty.png
    - assets/images/gallery.png
    - assets/images/student.png
    - assets/images/conatus.png
    - assets/images/logo-gif.gif
    - assets/images/menu.png
    - assets/images/back.png
    - assets/images/email.png
    - assets/images/dev-bg.jpg
    - assets/images/college.png
    - assets/images/lts.png
    - assets/images/home-bg.png
    - assets/images/circle.png
    - assets/images/conatua-text.png
    - assets/images/register-bg.jpeg
    - assets/images/gallery-bg.png
    - assets/images/c-bg.jpeg
    - assets/images/contactus.png
    - assets/images/m1.png
    - assets/images/fb.png
    - assets/images/insta.png
    - assets/images/team.jpg
    - assets/images/form.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
       - asset: assets/fonts/Ubuntu-Bold.ttf
       - asset: assets/fonts/Ubuntu-Light.ttf
       - asset: assets/fonts/Ubuntu-Medium.ttf
       - asset: assets/fonts/Ubuntu-Regular.ttf
         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
